### PR TITLE
[PKG-3035] umap-learn 0.5.4

### PR DESCRIPTION
**Pull request by Arishamays1**
[PKG-3035] umap-learn 0.5.4

upstream: https://github.com/lmcinnes/umap/tree/0.5.4
dependencies: https://github.com/lmcinnes/umap/blob/0.5.4/setup.py

destination channel: `defaults`

conda-forge: https://github.com/conda-forge/umap-learn-feedstock

actions:
- clean the `meta.yaml`, remove cross compilation 
- use `LICENSE.txt` file from the upstream
- patch `setup.py` to remove `tbb` dependency,  which was causing `pip check` to fail and would leave the user's environment not clean.
- add tests (source from GitHub archive)
- do not install tensor-flow for some tests (`jax` is missing for some tensor-flow python versions)
- set numpy<1.24.0 (see recipe)
- skip 1 test for `ppc64le` which gives seg fault
- dependency for AnacondaRecipes/bertopic-feedstock#2

other information about the `tbb` problem:
- https://github.com/lmcinnes/umap/issues/1054
- https://github.com/lmcinnes/umap/issues/1060#issuecomment-1749511918
- https://github.com/numba/numba/issues/7148

[PKG-3035]: https://anaconda.atlassian.net/browse/PKG-3035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
There is currently a pull request for this package that is open and needs to be closed

   it is version `0.5.3` and the pull request number is `1`
   here is a link to the pull request:
   https://github.com/AnacondaRecipes/umap-learn-feedstock/pull/1

**Comment by skupr-anaconda** [comment]
@Arishamays1 @lorepirri You can disable `pip check` as `tbb` is not a required dependency. The source code hasn't mentioned any usage of it. It's required by `numba`, see https://github.com/lmcinnes/umap/issues/1060#issuecomment-1749511918.
And leave a comment about why we disable it

**Comment by lorepirri** [comment]
> @Arishamays1 @lorepirri You can disable `pip check` as `tbb` is not a required dependency. The source code hasn't mentioned any usage of it. It's required by `numba`, see [lmcinnes/umap#1060 (comment)](https://github.com/lmcinnes/umap/issues/1060#issuecomment-1749511918). And leave a comment about why we disable it

Thank you @skupr-anaconda . Since the conclusion is that `tbb` is optional, I did patch the `setup.py` removing the `tbb` dependency, so now `pip check` runs without problems (in case the user wants to have a clean installation).

**Comment by skupr-anaconda** [comment]
> > @Arishamays1 @lorepirri You can disable `pip check` as `tbb` is not a required dependency. The source code hasn't mentioned any usage of it. It's required by `numba`, see [lmcinnes/umap#1060 (comment)](https://github.com/lmcinnes/umap/issues/1060#issuecomment-1749511918). And leave a comment about why we disable it
> 
> Thank you @skupr-anaconda . Since the conclusion is that `tbb` is optional, I did patch the `setup.py` removing the `tbb` dependency, so now `pip check` runs without problems (in case the user wants to have a clean installation).

But we should add `tbb` to `run` for `x86_64`

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Review by skupr-anaconda — APPROVED** [review]

**Comment by skupr-anaconda** [comment]
@lorepirri Did you forget to add abs.yaml with:
```
upload_channels:
  - sfe1ed40 
```

Because of:
`conda search umap-learn -c sfe1ed40`
```
Loading channels: done
# Name                       Version           Build  Channel
umap-learn                     0.5.3 py310hca03da5_0  pkgs/main
umap-learn                     0.5.3 py311hca03da5_0  pkgs/main
umap-learn                     0.5.3  py38hca03da5_0  pkgs/main
umap-learn                     0.5.3  py39hca03da5_0  pkgs/main
```

**Comment by lorepirri** [comment]
> @lorepirri Did you forget to add abs.yaml with:
> 
> ```
> upload_channels:
>   - sfe1ed40 
> ```
> 
> Because of: `conda search umap-learn -c sfe1ed40`
> 
> ```
> Loading channels: done
> # Name                       Version           Build  Channel
> umap-learn                     0.5.3 py310hca03da5_0  pkgs/main
> umap-learn                     0.5.3 py311hca03da5_0  pkgs/main
> umap-learn                     0.5.3  py38hca03da5_0  pkgs/main
> umap-learn                     0.5.3  py39hca03da5_0  pkgs/main
> ```

@skupr-anaconda originally `0.5.3` was for `defaults`
- https://anaconda.atlassian.net/browse/PKG-2191
- https://github.com/AnacondaRecipes/umap-learn-feedstock/pull/2

the command `conda search umap-learn -c sfe1ed40` shows also the ones in `defaults`, notice the column `Channel`:

```
% conda search umap-learn
Loading channels: done
# Name                       Version           Build  Channel             
umap-learn                     0.5.3 py310hca03da5_0  pkgs/main           
umap-learn                     0.5.3 py311hca03da5_0  pkgs/main           
umap-learn                     0.5.3  py38hca03da5_0  pkgs/main           
umap-learn                     0.5.3  py39hca03da5_0  pkgs/main
```

For example, another package that is only on SF, `json_stream`, will have the SF channel:

```
% conda search json_stream -c sfe1ed40
Loading channels: done
# Name                       Version           Build  Channel             
json_stream                    2.3.2 py310hca03da5_0  sfe1ed40            
json_stream                    2.3.2 py311hca03da5_0  sfe1ed40            
json_stream                    2.3.2  py38hca03da5_0  sfe1ed40            
json_stream                    2.3.2  py39hca03da5_0  sfe1ed40
```

**Review by Arishamays1 — COMMENTED** [review]
LGTM

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Comment by lorepirri** [comment]
@Arishamays1 I will merge this one and upload it.

**Pull request merged**
